CREATE DATABASE CHTH
USE CHTH
go

CREATE TABLE VAITRO(
	IDVaiTro INT IDENTITY(1, 1) PRIMARY KEY,
	TenVaiTro NVARCHAR(100) 
)

CREATE TABLE TAIKHOAN(
	IDTaiKhoan INT IDENTITY (1,1) PRIMARY KEY,
	IDQuanLy INT,
	HoTen NVARCHAR(100),
	SDT CHAR(10),
	Email NVARCHAR(100),
	MatKhau NVARCHAR(100),
	IDVaiTro INT
)

CREATE TABLE GIOHANG(
	IDGioHang INT IDENTITY(1, 1) PRIMARY KEY,
	IDTaiKhoan INT
)
CREATE TABLE PHANLOAI(
	IDPhanLoai INT IDENTITY(1, 1) PRIMARY KEY,
	Ten NVARCHAR(100),
	MoTa NVARCHAR(255)
)

CREATE TABLE SANPHAM(
	IDSanPham INT IDENTITY(1, 1) PRIMARY KEY,
	TenSanPham NVARCHAR(100),
	Gia DECIMAL(10, 2),
	MoTa NVARCHAR(255),
	TinhTrang NVARCHAR(100),
	IDPhanLoai INT
)

CREATE TABLE DANHGIA(
	IDDanhGia INT IDENTITY(1, 1) PRIMARY KEY,
	SoSao INT CHECK(SoSao BETWEEN 1 AND 5),
	BinhLuan NVARCHAR(255),
	ThoiGianTao DATETIME DEFAULT GETDATE(),
	IDSanPham INT,
	IDTaiKhoan INT
)

CREATE TABLE GIOHANG_SANPHAM(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	IDGioHang INT,
	IDSanPham INT,
	SoLuong INT
)

CREATE TABLE VOUCHER(
	IDVoucher INT IDENTITY(1, 1) PRIMARY KEY,
	MoTa NVARCHAR(255),
	GiamGia INT CHECK(GiamGia BETWEEN 1 AND 100), -- % GIẢM
	ToiDa DECIMAL(10, 2), -- Số tiền tối đa được giảm
	BatDau DATETIME,
	KetThuc DATETIME
)

CREATE TABLE DONHANG(
	IDDonHang INT IDENTITY(1, 1) PRIMARY KEY,
	IDTaiKhoan INT,
	TinhTrang NVARCHAR(255),
	PTTT NVARCHAR(100),
	NgayTao DATETIME DEFAULT GETDATE(),
	IDVoucher INT,
	TongTien DECIMAL(10, 2)
)

CREATE TABLE DONHANG_SANPHAM(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	IDDonHang INT,
	IDSanPham INT, 
	SoLuong INT
)

CREATE TABLE HANGTONKHO(
	IDHangTonKho INT IDENTITY(1, 1) PRIMARY KEY,
	Ten NVARCHAR(100),
	DonViTinh NVARCHAR(100),
	SoLuong DECIMAL(8, 2),
	NgayNhap DATETIME,
	IDQuanLy INT
)

ALTER TABLE TAIKHOAN 
ADD CONSTRAINT FK_TAIKHOAN_VAITRO FOREIGN KEY (IDVaiTro) REFERENCES VAITRO(IDVaiTro),
	CONSTRAINT FK_TAIKHOAN_QUANLY FOREIGN KEY (IDQuanLy) REFERENCES TAIKHOAN(IDTaiKhoan);

ALTER TABLE GIOHANG 
ADD CONSTRAINT FK_GIOHANG_TAIKHOAN FOREIGN KEY (IDTaiKhoan) REFERENCES TAIKHOAN(IDTaiKhoan);

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAM_PHANLOAI FOREIGN KEY (IDPhanLoai) REFERENCES PHANLOAI(IDPhanLoai);

ALTER TABLE DANHGIA
ADD CONSTRAINT FK_DANHGIA_SANPHAM FOREIGN KEY(IDSanPham) REFERENCES SANPHAM(IDSanPham),
	CONSTRAINT FK_DANHGIA_TAIKHOAN FOREIGN KEY(IDTaiKhoan) REFERENCES TAIKHOAN(IDTaiKhoan);
	

ALTER TABLE GIOHANG_SANPHAM
ADD CONSTRAINT FK_GIOHANGSANPHAM_GIOHANG FOREIGN KEY(IDGioHang) REFERENCES GIOHANG(IDGioHang),
	CONSTRAINT FK_GIOHANGSANPHAM_SANPHAM FOREIGN KEY(IDSanPham) REFERENCES SANPHAM(IDSanPham);
 
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_VOUCHER FOREIGN KEY(IDVoucher) REFERENCES VOUCHER(IDVoucher),
	CONSTRAINT FK_DONHANG_TAIKHOAN FOREIGN KEY(IDTaiKhoan) REFERENCES TAIKHOAN(IDTaiKhoan);

ALTER TABLE DONHANG_SANPHAM
ADD CONSTRAINT FK_DONHANGSANPHAM_DONHANG FOREIGN KEY(IDDonHang) REFERENCES DONHANG(IDDonHang),
	CONSTRAINT FK_DONHANGSANPHAM_SANPHAM FOREIGN KEY(IDSanPham) REFERENCES SANPHAM(IDSanPham);
 
ALTER TABLE HANGTONKHO
ADD CONSTRAINT FK_HANGTONKHO_QUANLY FOREIGN KEY(IDQuanLy) REFERENCES TAIKHOAN(IDTaiKhoan);


-- Vai trò
INSERT INTO VAITRO (TenVaiTro) VALUES
(N'Quản lý'),
(N'Nhân viên'),
(N'Khách hàng');

-- Tài khoản
INSERT INTO TAIKHOAN (IDQuanLy, HoTen, SDT, Email, MatKhau, IDVaiTro) VALUES
(null, N'Nguyễn Văn A', '0901234567', 'admin@example.com', '123456', 1), -- Quản lý 
(1, N'Trần Thị B', '0902345678', 'manager@example.com', '123456', 2),    -- Nhân viên ( được quản lý bởi quản lý Nguyễn Văn A, IDTK là 1)
(NULL, N'Lê Văn C', '0903456789', 'customer1@example.com', '123456', 3), -- Khách hàng
(NULL, N'Phạm Thị D', '0904567890', 'customer2@example.com', '123456', 3); -- Khách hàng

-- Giỏ hàng
INSERT INTO GIOHANG (IDTaiKhoan) VALUES
(3), -- giỏ hàng của khách hàng C
(4); -- giỏ hàng của khách hàng D

-- Phân loại sản phẩm
INSERT INTO PHANLOAI (Ten, MoTa) VALUES
(N'Trà sữa', N'Các loại trà sữa'),
(N'Cà phê', N'Các loại cà phê'),
(N'Nước ép', N'Các loại nước ép');

-- Sản phẩm
INSERT INTO SANPHAM (TenSanPham, Gia, MoTa, TinhTrang, IDPhanLoai) VALUES
(N'Trà sữa truyền thống', 30000, N'Ngon, ngọt vừa', N'Còn hàng', 1),
(N'Trà sữa matcha', 35000, N'Vị matcha thanh mát', N'Còn hàng', 1),
(N'Cà phê sữa đá', 25000, N'Cà phê đậm vị', N'Còn hàng', 2),
(N'Nước ép cam', 28000, N'Tươi ngon 100%', N'Còn hàng', 3);

-- Đánh giá
INSERT INTO DANHGIA (SoSao, BinhLuan, IDSanPham, IDTaiKhoan) VALUES
(5, N'Rất ngon!', 1, 3), -- C bình luận
(4, N'Ổn, hơi ngọt', 2, 3), -- C bình luận
(5, N'Cà phê thơm', 3, 4);	-- D bình luận

-- Giỏ hàng – sản phẩm
INSERT INTO GIOHANG_SANPHAM (IDGioHang, IDSanPham, SoLuong) VALUES
(1, 1, 2), -- C đặt 2 trà sữa truyền thống
(1, 3, 1), -- C đặt 1 cà phê sữa đá
(2, 2, 1); -- D đặt 1 trà sữa matcha

-- Voucher
INSERT INTO VOUCHER (MoTa, GiamGia, ToiDa, BatDau, KetThuc) VALUES
(N'Giảm 10%', 10, 20000, '2025-01-01', '2025-12-31'),
(N'Giảm 20%', 20, 30000, '2025-02-01', '2025-12-31');

-- Đơn hàng
INSERT INTO DONHANG (IDTaiKhoan, TinhTrang, PTTT, IDVoucher, TongTien) VALUES
(3, N'Đang xử lý', N'Thanh toán khi nhận hàng', 1, 85000),
(4, N'Hoàn thành', N'Thanh toán online', NULL, 35000);

-- Đơn hàng – sản phẩm
INSERT INTO DONHANG_SANPHAM (IDDonHang, IDSanPham, SoLuong) VALUES
(1, 1, 2), -- C đặt 2 trà sữa truyền thống
(1, 3, 1), -- C đặt 1 cà phê sữa đá
(2, 2, 1); -- D đặt 1 trà sữa matcha

-- Hàng tồn kho
INSERT INTO HANGTONKHO (Ten, DonViTinh, SoLuong, NgayNhap, IDQuanLy) VALUES
(N'Trà sữa truyền thống', N'Ly', 100, GETDATE(), 1),
(N'Trà sữa matcha', N'Ly', 50, GETDATE(), 1),
(N'Cà phê sữa đá', N'Ly', 200, GETDATE(), 1),
(N'Nước ép cam', N'Ly', 80, GETDATE(), 1);

SELECT * FROM VAITRO
SELECT * FROM TAIKHOAN
SELECT * FROM GIOHANG
SELECT * FROM PHANLOAI
SELECT * FROM SANPHAM
SELECT * FROM DANHGIA
SELECT * FROM GIOHANG_SANPHAM
SELECT * FROM VOUCHER
SELECT * FROM DONHANG
SELECT * FROM DONHANG_SANPHAM
SELECT * FROM HANGTONKHO

SELECT * FROM TAIKHOAN


ALTER TABLE TAIKHOAN DROP COLUMN VaiTroId;

SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'TAIKHOAN';

SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Sanpham';

ALTER TABLE TAIKHOAN
ADD DiaChi NVARCHAR(250) NULL;

ALTER TABLE TAIKHOAN
ADD ResetToken NVARCHAR(100) NULL;

ALTER TABLE TAIKHOAN
ADD ResetTokenExpire DATETIME NULL;

ALTER TABLE Sanpham
ADD ImageUrl NVARCHAR(250) NULL;
