// <auto-generated />
using System;
using DrinkShop.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrinkShop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrinkShop.Domain.Entities.CongThuc", b =>
                {
                    b.Property<int>("IDCongThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCongThuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCongThuc"));

                    b.Property<int>("IDNguyenLieu")
                        .HasColumnType("int")
                        .HasColumnName("IDNguyenLieu");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int")
                        .HasColumnName("IDSanPham");

                    b.Property<double>("SoLuongCan")
                        .HasColumnType("float")
                        .HasColumnName("SoLuongCan");

                    b.HasKey("IDCongThuc");

                    b.HasIndex("IDNguyenLieu");

                    b.HasIndex("IDSanPham");

                    b.ToTable("CongThuc", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.DanhGia", b =>
                {
                    b.Property<int>("IDDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDanhGia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDanhGia"));

                    b.Property<string>("BinhLuan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BinhLuan");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int")
                        .HasColumnName("IDSanPham");

                    b.Property<int>("IDTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("IDTaiKhoan");

                    b.Property<int>("SoSao")
                        .HasColumnType("int")
                        .HasColumnName("SoSao");

                    b.Property<DateTime>("ThoiGianTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianTao")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("IDDanhGia");

                    b.HasIndex("IDSanPham");

                    b.HasIndex("IDTaiKhoan");

                    b.ToTable("DANHGIA", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.DonHang", b =>
                {
                    b.Property<int>("IDDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDonHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDonHang"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("IDTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("IDTaiKhoan");

                    b.Property<int?>("IDVoucher")
                        .HasColumnType("int")
                        .HasColumnName("IDVoucher");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PTTT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PTTT");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("TinhTrang");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unpaid")
                        .HasColumnName("TrangThaiThanhToan");

                    b.HasKey("IDDonHang");

                    b.HasIndex("IDTaiKhoan");

                    b.HasIndex("IDVoucher");

                    b.ToTable("DONHANG", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.DonHangSanPham", b =>
                {
                    b.Property<int>("IDDonHangSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDonHangSanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDonHangSanPham"));

                    b.Property<decimal>("GiaDonVi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaDonVi");

                    b.Property<int>("IDDonHang")
                        .HasColumnType("int")
                        .HasColumnName("IDDonHang");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int")
                        .HasColumnName("IDSanPham");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("IDDonHangSanPham");

                    b.HasIndex("IDDonHang");

                    b.HasIndex("IDSanPham");

                    b.ToTable("DONHANG_SANPHAM", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.GioHang", b =>
                {
                    b.Property<int>("IDGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDGioHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDGioHang"));

                    b.Property<int>("IDTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("IDTaiKhoan");

                    b.HasKey("IDGioHang");

                    b.HasIndex("IDTaiKhoan")
                        .IsUnique();

                    b.ToTable("GIOHANG", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.GioHangSanPham", b =>
                {
                    b.Property<int>("IDGioHangSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDGioHangSanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDGioHangSanPham"));

                    b.Property<int>("IDGioHang")
                        .HasColumnType("int")
                        .HasColumnName("IDGioHang");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int")
                        .HasColumnName("IDSanPham");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("IDGioHangSanPham");

                    b.HasIndex("IDGioHang");

                    b.HasIndex("IDSanPham");

                    b.ToTable("GIOHANG_SANPHAM", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.HangTonKho", b =>
                {
                    b.Property<int>("IDHangTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDHangTonKho");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHangTonKho"));

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DonViTinh");

                    b.Property<int?>("IDQuanLy")
                        .HasColumnType("int")
                        .HasColumnName("IDQuanLy");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int")
                        .HasColumnName("IDSanPham");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayNhap");

                    b.Property<decimal?>("SoLuong")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("SoLuong");

                    b.Property<int?>("TaiKhoanIDTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ten");

                    b.HasKey("IDHangTonKho");

                    b.HasIndex("IDQuanLy");

                    b.HasIndex("IDSanPham");

                    b.HasIndex("TaiKhoanIDTaiKhoan");

                    b.ToTable("HANGTONKHO", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.LichSuKho", b =>
                {
                    b.Property<int>("IDLichSuKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDLichSuKho"));

                    b.Property<int>("IDNguyenLieu")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NguoiThucHien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SoLuongSauKhiDoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoLuongThayDoi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IDLichSuKho");

                    b.HasIndex("IDNguyenLieu");

                    b.ToTable("LichSuKhos", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.NguyenLieu", b =>
                {
                    b.Property<int>("IDNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDNguyenLieu"));

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("SoLuongTon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNguyenLieu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IDNguyenLieu");

                    b.ToTable("NguyenLieu", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.PhanLoai", b =>
                {
                    b.Property<int>("IDPhanLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPhanLoai"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDPhanLoai");

                    b.ToTable("PHANLOAI", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.SanPham", b =>
                {
                    b.Property<int>("IDSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDSanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSanPham"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Gia");

                    b.Property<int>("IDPhanLoai")
                        .HasColumnType("int")
                        .HasColumnName("IDPhanLoai");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ImageUrl");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MoTa");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSanPham");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TinhTrang");

                    b.HasKey("IDSanPham");

                    b.HasIndex("IDPhanLoai");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("IDTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTaiKhoan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTaiKhoan"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Avatar");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<int?>("IDQuanLy")
                        .HasColumnType("int")
                        .HasColumnName("IDQuanLy");

                    b.Property<int?>("IDVaiTro")
                        .HasColumnType("int")
                        .HasColumnName("IDVaiTro");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("RefreshToken");

                    b.Property<DateTime?>("RefreshTokenExpire")
                        .HasColumnType("datetime2")
                        .HasColumnName("RefreshTokenExpire");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ResetToken");

                    b.Property<DateTime?>("ResetTokenExpire")
                        .HasColumnType("datetime2")
                        .HasColumnName("ResetTokenExpire");

                    b.Property<string>("SDT")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SDT");

                    b.HasKey("IDTaiKhoan");

                    b.HasIndex("IDQuanLy");

                    b.HasIndex("IDVaiTro");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.VaiTro", b =>
                {
                    b.Property<int>("IDVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDVaiTro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDVaiTro"));

                    b.Property<string>("Permission")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Permission");

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenVaiTro");

                    b.HasKey("IDVaiTro");

                    b.ToTable("VAITRO", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.Voucher", b =>
                {
                    b.Property<int>("IDVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDVoucher");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDVoucher"));

                    b.Property<DateTime?>("BatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("BatDau");

                    b.Property<decimal>("DieuKienMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("DieuKienMin");

                    b.Property<int?>("GiamGia")
                        .HasColumnType("int")
                        .HasColumnName("GiamGia");

                    b.Property<DateTime?>("KetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("KetThuc");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MoTa");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<int>("SoLuongConLai")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongConLai");

                    b.Property<decimal?>("ToiDa")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ToiDa");

                    b.HasKey("IDVoucher");

                    b.ToTable("VOUCHER", (string)null);
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.CongThuc", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("CongThucs")
                        .HasForeignKey("IDNguyenLieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrinkShop.Domain.Entities.SanPham", "SanPham")
                        .WithMany("CongThucs")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.DanhGia", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrinkShop.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DanhGias")
                        .HasForeignKey("IDTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.DonHang", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DonHangs")
                        .HasForeignKey("IDTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrinkShop.Domain.Entities.Voucher", "Voucher")
                        .WithMany("DonHang")
                        .HasForeignKey("IDVoucher")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.DonHangSanPham", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IDDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrinkShop.Domain.Entities.SanPham", "SanPham")
                        .WithMany("DonHangSanPhams")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.GioHang", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("GioHang")
                        .HasForeignKey("DrinkShop.Domain.Entities.GioHang", "IDTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.GioHangSanPham", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.GioHang", "GioHang")
                        .WithMany("GioHangSanPhams")
                        .HasForeignKey("IDGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrinkShop.Domain.Entities.SanPham", "SanPham")
                        .WithMany("GioHangSanPhams")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.HangTonKho", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.TaiKhoan", "QuanLy")
                        .WithMany()
                        .HasForeignKey("IDQuanLy");

                    b.HasOne("DrinkShop.Domain.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrinkShop.Domain.Entities.TaiKhoan", null)
                        .WithMany("HangTonKhos")
                        .HasForeignKey("TaiKhoanIDTaiKhoan");

                    b.Navigation("QuanLy");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.LichSuKho", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("LichSuKhos")
                        .HasForeignKey("IDNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.SanPham", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.PhanLoai", "PhanLoai")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDPhanLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhanLoai");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.TaiKhoan", b =>
                {
                    b.HasOne("DrinkShop.Domain.Entities.TaiKhoan", "QuanLy")
                        .WithMany()
                        .HasForeignKey("IDQuanLy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrinkShop.Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IDVaiTro");

                    b.Navigation("QuanLy");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.GioHang", b =>
                {
                    b.Navigation("GioHangSanPhams");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.NguyenLieu", b =>
                {
                    b.Navigation("CongThucs");

                    b.Navigation("LichSuKhos");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.PhanLoai", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.SanPham", b =>
                {
                    b.Navigation("CongThucs");

                    b.Navigation("DanhGias");

                    b.Navigation("DonHangSanPhams");

                    b.Navigation("GioHangSanPhams");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.TaiKhoan", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHang");

                    b.Navigation("HangTonKhos");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DrinkShop.Domain.Entities.Voucher", b =>
                {
                    b.Navigation("DonHang");
                });
#pragma warning restore 612, 618
        }
    }
}
